### ISSUE TITLE
ssh config file (~/.ssh/config) causes a bug when launching remote nodes

### ISSUE THREAD

**Issue by klpanagi** [pandora-auth-ros-pkg/deployment-scripts#2]
## *\* Reported bug **

roslaunch pandora_launchers rpi_flir.launch 
... logging to /home/pandora/.ros/log/2b3dff70-18dc-11e5-997c-00032d258a7f/roslaunch-pandora-gears-11514.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.0.106:55602/
remote[rpi2-0] starting roslaunch
remote[rpi2-0]: creating ssh connection to rpi2:22, user[pandora]
Traceback (most recent call last):
 File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/**init**.py", line 279, in main
   p.start()
 File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/parent.py", line 257, in start
   self._start_infrastructure()
 File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/parent.py", line 219, in _start_infrastructure
   self._start_remote()
 File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/parent.py", line 199, in _start_remote
   self.remote_runner.start_children()
 File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/remote.py", line 124, in start_children
   p = self._start_child(server_node_uri, machines[m], counter)
 File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/remote.py", line 94, in _start_child
   success = p.start()
 File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/remoteprocess.py", line 226, in start
   sshvals, msg = self._ssh_exec(' '.join(self.args), m.address, m.ssh_port, m.user, m.password)
 File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/remoteprocess.py", line 175, in _ssh_exec
   identity_file = os.path.expanduser(config_block['identityfile'])
 File "/usr/lib/python2.7/posixpath.py", line 252, in expanduser
   if not path.startswith('~'):
AttributeError: 'list' object has no attribute 'startswith'

**Comment by klpanagi** [comment]
The error is produced as **remoteprocess.py** loads the ssh identity-file registerd to the relevant machine in a _list_ format instead of _String_ format
